# Generated by Django 4.2.25 on 2025-11-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('master', '0003_itemdetail_alt_uom_itemdetail_opening_stock_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='itemdetail',
            name='opening_stock',
        ),
        migrations.AlterField(
            model_name='customerdetail',
            name='opening_balance',
            field=models.DecimalField(decimal_places=2, max_digits=15),
        ),
        migrations.AlterField(
            model_name='itemdetail',
            name='item_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
