# Generated by Django 4.2.25 on 2025-11-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finished_goods', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='packingslip',
            name='trans_to',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='packingslipitem',
            name='item_code',
            field=models.CharField(blank=True, max_length=50, null=True, unique=True),
        ),
    ]
