# Generated by Django 4.2.25 on 2025-11-18 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('packing_materials', '0005_alter_packinginwardmaterial_grn_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='packinginwardmaterial',
            name='grn_no',
            field=models.CharField(default=1, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='uploadedfile',
            name='upload_date',
            field=models.DateField(),
        ),
    ]
